name: GuarlicPlug
version: '1.1'
main: guarlicplug.guarlicplug.Main
api-version: 1.19
authors: [ Guarlic ]
website: 'https://github.com/Guarlic/GuarlicPlug'
description: Guarlic Server Plugin
commands:
  happy:
    description: 'Use when you feels happy!'
    aliases: [ h ]
  angry:
    description: 'Use when you feels angry!'
    aliases: [ a ]
  inv:
    description: 'Special inventory'
  cooldown_reset:
    description: 'Reset cooldown of everyone'